### ISSUE TITLE
How to add babel-polyfills or any other js library

### ISSUE THREAD

**Issue by zidjian257** [glimmerjs/glimmer.js#18]
Hi all,

in #8 we were talking about IE compabilities where it was suggested to add babel-polyfills.
I already asked in the #8 issue about what would be the right way in glimmerjs to add the library, but I  didn't get an answer yet and anyhow it got lost in comments I guess.

So I guess it's better to move this question to a seperate issue, so other peaple can find it easier if they are facing the same problem.

The way I did it is just add the js file as an external script in my index.html, but I'm sure there is a better way to include it.

npm install babel-polyfill and adding require('babel-polyfill') to the ember-cli-build.js file did not help.

Also using ember-cli-babel plugin and add 'ember-cli-babel': { includePolyfill: true } to the ember-cli-build.js resulted in an error as glimmerjs does not support app.import.

Would be great if someone could tell me how to add libraries the right way to a glimmerjs app.

**Comment by tschoartschi** [comment]
I'm not sure if this is really an issue or more a discussion because we use a completely different approach. We included a small inline script in `index.html` which detects which polyfill is needed and then loads them on demand. After all polyfills are loaded we start the glimmer app. This has the advantage the polyfills are not shipped to every browser. So the payload is small for modern browsers and maybe bigger for legacy browsers. I think you should only ship what's needed and not everything that could be needed by some old IE9 browser.

Libraries we also load async (we use three.js for example). This has some advantages for us, one thing is that `app.js` stays small which improves load and parse time. Furthermore, we can decide when to load what, this improves time-to-interactive for us. Also we have fine-grained control on cache-invalidation. If three.js would be included into `app.js` the user would have to fetch everything again even if we only do small changes to our code, which means load our-code and three.js (because it's one file). 

So I think it depends on the use case to decide what's the best way to include a library

**Comment by john-griffin** [comment]
Having this issue too. We are just looking for an example of how to activate the babel polyfill using the glimmer application pipeline. It's clear how to do this in ember but not in glimmer.

**Comment by tomdale** [comment]
Getting `babel-polyfill` working with a Glimmer app *should* be pretty straightforward.

Here are the steps I used in a test app that seemed to work:

1. `yarn add babel-polyfill` to install the package as a dependency of the app.
2. In the app's main entry point (`index.ts`), add `import "babel-polyfill/browser";` as the first line.
3. There is no step 3!

Under the hood, the build is using Rollup for packaging, so any package that works with Rollup should "just work." One unfortunate thing about `babel-polyfill` is that it is not using JavaScript module syntax, so if you import `babel-polyfill` you will get an error when it tries to call `require()`. The workaround is pretty easy, though: import the browser build at `babel-polyfill/browser`.

Let me know how that works out!

**Comment by t-sauer** [comment]
Since Glimmer.js apps are using babel-preset-env already, wouldn't it make sense to add babel-polyfill by default, and use the `useBuiltIns` option of it? This will help to only include the polyfills that are actually needed for a given set of targets. Also with Babel 7 `useBuiltIns` can be configured to only include polyfills that are actually needed (based on usage).

**Comment by tomdale** [comment]
@t-sauer I would definitely be open to making the defaults better. Is this something that can be easily configured already or are you proposing a new feature?

**Comment by john-griffin** [comment]
Thanks Tom, your suggestion worked for me. Now running in IE11!

Agree with @t-sauer - would be great to have this baked into the pipeline.

**Comment by t-sauer** [comment]
@tomdale I think we have multiple options:

1. Include all of babel-polyfill by default. Could be done by users, so no additional feature needed.
2. Include babel-polyfill by default, add the import to the index.ts, change the babel-preset-env configuration to transpile the imports to only the required ones (basically make use of `useBuiltIns: true` in Babel 6). This could either be done by the user (adding the package and configure the babel options) or if this should be the default, this needs some minor work in both the blueprint and application-pipeline.
3. Go for the Babel 7 beta and configure babel-preset-env with `useBuiltIns: 'usage'`. If Babel sees something that needs to be polyfilled, an import will be added automatically for that specific thing and Rollup will take care of the rest. This would need changes in the application-pipeline.

I think the third solution is the best since it will yield the best result and you don't have to have a possible confusing import in your index.ts. I also already tried it out a couple of days ago but had some minor issues, which I am confident to get solved.

**Comment by rwjblue** [comment]
Agreed. The third option is definitely preferable.

**Comment by tomdale** [comment]
@t-sauer Sounds awesome, looking forward to your PR!
