### ISSUE TITLE
Using `tracked` without decorators

### ISSUE THREAD

**Issue by chicoxyzzy** [glimmerjs/glimmer.js#22]
It could be useful to have docs about using `tracked` in function form instead of decorator form. `experimentalDecorators` from TypeScript and decorators from [ECMAScript proposal](https://github.com/tc39/proposal-decorators) are not the same thing. Also it'll be useful for people who prefer to use current version of JavaScript.

**Comment by tomdale** [comment]
Can you a show a straw man version of the API you’ve got in mind?

**Comment by chicoxyzzy** [comment]
I had no time to investigate it yet but maybe API could look like [mobx' `extendObservable`](https://mobx.js.org/best/decorators.html)

**Comment by tomdale** [comment]
@chicoxyzzy The approached used by MobX would not be a good fit for Glimmer, I don't think. One cool thing about how tracked properties work right now is that the getter and setter are only configured one time per component, on the prototype. This makes instantiating a new component instance very cheap because there's almost no work to do.

In the `extendObservable` API, [there's a non-trivial cost at class construction time](https://github.com/mobxjs/mobx/blob/a867e87788a3aeb5d03a0a99f8379c13edd6be25/src/api/extendobservable.ts#L30-L52).

I'm definitely not opposed to offering a non-decorator API for configuring tracked properties, but we would need to come up with something that is both ergonomic and maintains the semantics and performance characteristics of the decorator API.

**Comment by rwjblue** [comment]
Well, AFAICT, it should be possible to do this without decorators (but using the exported decorator function) already:

```js
import Component, { tracked } from '@glimmer/component';

class Foo extends Component { }
tracked(Foo.prototype, 'name'); // to mark a property as tracked
tracked('firstName', 'lastName')(Foo.prototype, 'name', {
  get() {
    return `${this.firstName} ${this.lastName}`;
  }
});
```

Am I missing something?

**Comment by tomdale** [comment]
@rwjblue Yep, great point, that works already. I guess there's a question of whether we want to provide some syntactic sugar for this case, something like:

```js
import Component, { extendTracked } from '@glimmer/component';

class Foo extends Component { }

extendTracked(Foo, {
  name: 'Rob Jackson', // annotates name as tracked and sets initial value
  firstName: { // annotates firstName as a tracked property with a getter and one dependent key
    get() {
      return this.name.split(' ')[0];
    },
    keys: ['name']
  }
});
```

However, this doesn't seem appreciably better to me than the example you gave and I don't really want to get in the business of inventing Glimmer-specific versions of functionality that is coming to the language soon anyway.

**Comment by chicoxyzzy** [comment]
@rwjblue I think your examples look good enough 👍. It'll be great if examples of using `tracked` without decorators will be documented.

**Comment by acorncom** [comment]
@chicoxyzzy would you have time to send in a PR to document the above? Seems like it'd be a good fit in the API documentation (leaving the guides for more general interest docs ...)

**Comment by locks** [comment]
This should be resolved as per the discussion, closing. Thanks for your time everyone!
