### ISSUE TITLE
@tracked doesn't track date changes that doesn't imply an assignment

### ISSUE THREAD

**Issue by MarcoUmpierrez** [glimmerjs/glimmer.js#222]
Basically what the title says. For example:
```js
// this doesn't work
@action changeDate() {
  this.date.setDate(this.date.getDate() - 1);
}
```
This changes the date value but `tracked` doesn't detect it. Assigning it to itself makes `tracked` to be aware of the change:
```js
// this works
@action changeDate() {
  this.date.setDate(this.date.getDate() - 1);
  this.date = this.date;
}
```

**Comment by pzuraq** [comment]
`@tracked` does not deep track changes, it only tracks the property itself, so this is expected behavior. If you're interested in deep tracking, and are an Ember user, consider looking at https://github.com/pzuraq/tracked-built-ins for an example of how various classes that autotrack can be built. It sounds like you may want to create a `TrackedDate` class.

**Comment by MarcoUmpierrez** [comment]
Thanks @pzuraq for the clarification and suggestion. I didn't realize that changing a date value indirectly was a deep change.
