### ISSUE TITLE
Very slow render of grid of divs with tooltips

### ISSUE THREAD

**Issue by BryanCrotaz** [glimmerjs/glimmer.js#300]
28x28 divs with tooltips is taking 964ms to render on a dev desktop. Is this too much for Glimmer and I should optimise, or is there an optimisation case here for glimmer?

```
  <div class="t">
    {{#each this.heatmap as |row rowindex|}}
    <div class="r">
      {{#each row as |cellValue colindex|}}
      <div class="c" style={{color-scale cellValue min=25 max=65}}>
        <BsTooltip @placement="auto" class="small">
          <p class="mb-0 pb-0">
            Module {{add colindex 1}}:{{add rowindex 1}}
          </p>
          <p class="mb-0 pb-0 lead">
            {{cellValue}}&#8451;
          </p>
        </BsTooltip>
      </div>
      {{/each}}
    </div>
```

![image](https://user-images.githubusercontent.com/2016523/90978231-246ecf00-e544-11ea-99ee-a23a5f2ef1ce.png)

**Comment by lifeart** [comment]
@BryanCrotaz try to measure performance in production mode, dev may be up to 5 times slower due to extended debug info and additional checks

**Comment by pzuraq** [comment]
Also is this for an Ember app? It may be better to add this to Ember's issue tracker instead, as Ember does have more overhead for some of its own internals.

That said, @lifeart is correct, you should should be sure to measure a production build instead of development. You can see the `runInAutotrackingTransaction` calls in the callstack you posted, which are an indicator that this is a development build.

**Comment by chriskrycho** [comment]
I would look at `BsTooltip` and see what it's doing. The 28×28 grid itself is *suuuuper* fast, even on dev.
