### ISSUE TITLE
Better Warning For @tracked properties

### ISSUE THREAD

**Issue by chadhietala** [glimmerjs/glimmer.js#42]
Given:

```ts
class Foo {
  foo = 'Foo'

  @tracked('foo')
  get bar() {
    return `${this.foo}-bar`
  }
}
```

In the example about the `bar`getter has a dependency on `foo` however `foo` cannot change. I believe the correct thing to do here is give a nice warning message about the dependency not being `@tracked`. This will allow users know why exactly things are not updating.

**Comment by c0urg3tt3** [comment]
reading the [test](https://github.com/glimmerjs/glimmer.js/blob/master/packages/%40glimmer/component/test/browser/tracked-property-test.ts#L9) for [tracked property](https://github.com/glimmerjs/glimmer.js/blob/master/packages/%40glimmer/component/src/tracked.ts#L236), it looks like an error is thrown in DEBUG mode (development) ... but not otherwise.

i just tested the behaviour on a sample project and got a nice warning message.

`Uncaught UntrackedPropertyError: The 'state' property on the date-picker component was changed after it had been rendered. Properties that change after being rendered must be tracked. Use the @tracked decorator to mark this as a tracked property.`

am i missing something ?

**Comment by Turbo87** [comment]
@chadhietala @tomdale  is this still relevant?

**Comment by locks** [comment]
No longer relevant!
