### ISSUE TITLE
Can a glimmer addon be created to pull in 3rd party code?

### ISSUE THREAD

**Issue by BryanCrotaz** [glimmerjs/glimmer.js#6]
I want to use greensock in a glimmer component. There is ember-gsap - if I npm install this will it work?

There are no docs regarding installing addons - it would be useful to know what one needs to do with initialisers etc to set up an addon for glimmer

**Comment by BryanCrotaz** [comment]
Or even whether or not it's possible

**Comment by tomdale** [comment]
Hey Bryan, Glimmer uses Rollup to package the bundle and resolve external dependencies. If GreenSock is compatible with Rollup, you should be able to install it using `yarn` and import it directly into your components. The `ember-gsap` library won't work because Ember addons are not supported at the moment.
